USE [master]
GO
/****** Object:  Database [KarnelTravel]    Script Date: 12/10/2019 07:20:50 PM ******/
CREATE DATABASE [KarnelTravel]
GO
ALTER DATABASE [KarnelTravel] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KarnelTravel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KarnelTravel] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KarnelTravel] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KarnelTravel] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KarnelTravel] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KarnelTravel] SET ARITHABORT OFF 
GO
ALTER DATABASE [KarnelTravel] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [KarnelTravel] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [KarnelTravel] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KarnelTravel] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KarnelTravel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KarnelTravel] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KarnelTravel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KarnelTravel] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KarnelTravel] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KarnelTravel] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KarnelTravel] SET  DISABLE_BROKER 
GO
ALTER DATABASE [KarnelTravel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KarnelTravel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KarnelTravel] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KarnelTravel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KarnelTravel] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KarnelTravel] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KarnelTravel] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KarnelTravel] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [KarnelTravel] SET  MULTI_USER 
GO
ALTER DATABASE [KarnelTravel] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KarnelTravel] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KarnelTravel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KarnelTravel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [KarnelTravel] SET  READ_WRITE 
GO
USE [KarnelTravel]
GO

/****** Object:  Table [dbo].[Employees]    Script Date: 12/10/2019 07:20:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LoginName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
	[EmployeeName] [nvarchar](50) NOT NULL,
	[Phone] [nchar](20) NULL,
	[Email] [nchar](200) NULL,
	[Address] [nvarchar](200) NULL,
	[LevelId] [int] NULL,
	[LastLogin] [datetime] NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[LevelPermissions]    Script Date: 12/10/2019 07:20:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LevelPermissions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LevelId] [int] NOT NULL,
	[TableName] [nvarchar](50) NULL,
	[DisplayName] [nvarchar](100)  NULL,
	[AllowPermission] [int] NULL,
 CONSTRAINT [PK_LevelPermissions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[Levels]    Script Date: 12/10/2019 07:20:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Levels](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LevelName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Levels] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Index [UQ__Employee__DB8464FF8A891409]    Script Date: 12/10/2019 07:20:50 PM ******/
ALTER TABLE [dbo].[Employees] ADD UNIQUE NONCLUSTERED 
(
	[LoginName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_FK_Employees_Levels]    Script Date: 12/10/2019 07:20:50 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_FK_Employees_Levels] ON [dbo].[Employees]
(
	[LoginName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_LevelLevelPermission]    Script Date: 12/10/2019 07:20:50 PM ******/
CREATE NONCLUSTERED INDEX [IX_FK_LevelLevelPermission] ON [dbo].[LevelPermissions]
(
	[LevelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LevelPermissions] ADD  CONSTRAINT [DF_LevelPermissions_AllowPermission]  DEFAULT ((0)) FOR [AllowPermission]
GO

ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [FK_Employees_Levels] FOREIGN KEY([LevelId])
REFERENCES [dbo].[Levels] ([Id])
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [FK_Employees_Levels]
GO
ALTER TABLE [dbo].[LevelPermissions]  WITH CHECK ADD  CONSTRAINT [FK_LevelLevelPermission] FOREIGN KEY([LevelId])
REFERENCES [dbo].[Levels] ([Id])
GO
ALTER TABLE [dbo].[LevelPermissions] CHECK CONSTRAINT [FK_LevelLevelPermission]
GO


/****** Object:  Table [dbo].[Customers]    Script Date: 16/10/2019 08:10:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
	[Password] [nvarchar](100) NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](200) NOT NULL,
	[VIP] [int] NOT NULL,
 CONSTRAINT [PK_Customers_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO